select 
CHILD.ID, 
CHILD.GENOTYPE, 
PARENT.GENOTYPE AS PARENT_GENOTYPE 
from ECOLI_DATA AS CHILD
INNER JOIN ECOLI_DATA AS PARENT
ON CHILD.PARENT_ID = PARENT.ID
WHERE CHILD.PARENT_ID IS NOT NULL
AND (CHILD.GENOTYPE & PARENT.GENOTYPE) = PARENT.GENOTYPE
ORDER BY CHILD.ID